# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: single_node/agent_swarm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'single_node/agent_swarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsingle_node/agent_swarm.proto\x12\nagentswarm\"P\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\"/\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"`\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x11\n\tembedding\x18\x05 \x03(\x02\"9\n\x13VectorSearchRequest\x12\x17\n\x0fquery_embedding\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"W\n\x12VectorSearchResult\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"G\n\x14VectorSearchResponse\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.agentswarm.VectorSearchResult2\xcf\x01\n\nAgentSwarm\x12\x36\n\x03Put\x12\x16.agentswarm.PutRequest\x1a\x17.agentswarm.PutResponse\x12\x36\n\x03Get\x12\x16.agentswarm.GetRequest\x1a\x17.agentswarm.GetResponse\x12Q\n\x0cVectorSearch\x12\x1f.agentswarm.VectorSearchRequest\x1a .agentswarm.VectorSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'single_node.agent_swarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=45
  _globals['_PUTREQUEST']._serialized_end=125
  _globals['_PUTRESPONSE']._serialized_start=127
  _globals['_PUTRESPONSE']._serialized_end=174
  _globals['_GETREQUEST']._serialized_start=176
  _globals['_GETREQUEST']._serialized_end=201
  _globals['_GETRESPONSE']._serialized_start=203
  _globals['_GETRESPONSE']._serialized_end=299
  _globals['_VECTORSEARCHREQUEST']._serialized_start=301
  _globals['_VECTORSEARCHREQUEST']._serialized_end=358
  _globals['_VECTORSEARCHRESULT']._serialized_start=360
  _globals['_VECTORSEARCHRESULT']._serialized_end=447
  _globals['_VECTORSEARCHRESPONSE']._serialized_start=449
  _globals['_VECTORSEARCHRESPONSE']._serialized_end=520
  _globals['_AGENTSWARM']._serialized_start=523
  _globals['_AGENTSWARM']._serialized_end=730
# @@protoc_insertion_point(module_scope)
