// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: single_node/agent_swarm.proto

#include "single_node/agent_swarm.pb.h"
#include "single_node/agent_swarm.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace agentswarm {

static const char* AgentSwarm_method_names[] = {
  "/agentswarm.AgentSwarm/Put",
  "/agentswarm.AgentSwarm/Get",
  "/agentswarm.AgentSwarm/VectorSearch",
};

std::unique_ptr< AgentSwarm::Stub> AgentSwarm::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AgentSwarm::Stub> stub(new AgentSwarm::Stub(channel, options));
  return stub;
}

AgentSwarm::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Put_(AgentSwarm_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(AgentSwarm_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VectorSearch_(AgentSwarm_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AgentSwarm::Stub::Put(::grpc::ClientContext* context, const ::agentswarm::PutRequest& request, ::agentswarm::PutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agentswarm::PutRequest, ::agentswarm::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Put_, context, request, response);
}

void AgentSwarm::Stub::async::Put(::grpc::ClientContext* context, const ::agentswarm::PutRequest* request, ::agentswarm::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agentswarm::PutRequest, ::agentswarm::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void AgentSwarm::Stub::async::Put(::grpc::ClientContext* context, const ::agentswarm::PutRequest* request, ::agentswarm::PutResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agentswarm::PutResponse>* AgentSwarm::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::agentswarm::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agentswarm::PutResponse, ::agentswarm::PutRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Put_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agentswarm::PutResponse>* AgentSwarm::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::agentswarm::PutRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentSwarm::Stub::Get(::grpc::ClientContext* context, const ::agentswarm::GetRequest& request, ::agentswarm::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agentswarm::GetRequest, ::agentswarm::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void AgentSwarm::Stub::async::Get(::grpc::ClientContext* context, const ::agentswarm::GetRequest* request, ::agentswarm::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agentswarm::GetRequest, ::agentswarm::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void AgentSwarm::Stub::async::Get(::grpc::ClientContext* context, const ::agentswarm::GetRequest* request, ::agentswarm::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agentswarm::GetResponse>* AgentSwarm::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::agentswarm::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agentswarm::GetResponse, ::agentswarm::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agentswarm::GetResponse>* AgentSwarm::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::agentswarm::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentSwarm::Stub::VectorSearch(::grpc::ClientContext* context, const ::agentswarm::VectorSearchRequest& request, ::agentswarm::VectorSearchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agentswarm::VectorSearchRequest, ::agentswarm::VectorSearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VectorSearch_, context, request, response);
}

void AgentSwarm::Stub::async::VectorSearch(::grpc::ClientContext* context, const ::agentswarm::VectorSearchRequest* request, ::agentswarm::VectorSearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agentswarm::VectorSearchRequest, ::agentswarm::VectorSearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VectorSearch_, context, request, response, std::move(f));
}

void AgentSwarm::Stub::async::VectorSearch(::grpc::ClientContext* context, const ::agentswarm::VectorSearchRequest* request, ::agentswarm::VectorSearchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VectorSearch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agentswarm::VectorSearchResponse>* AgentSwarm::Stub::PrepareAsyncVectorSearchRaw(::grpc::ClientContext* context, const ::agentswarm::VectorSearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agentswarm::VectorSearchResponse, ::agentswarm::VectorSearchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VectorSearch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agentswarm::VectorSearchResponse>* AgentSwarm::Stub::AsyncVectorSearchRaw(::grpc::ClientContext* context, const ::agentswarm::VectorSearchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVectorSearchRaw(context, request, cq);
  result->StartCall();
  return result;
}

AgentSwarm::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentSwarm_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentSwarm::Service, ::agentswarm::PutRequest, ::agentswarm::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentSwarm::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agentswarm::PutRequest* req,
             ::agentswarm::PutResponse* resp) {
               return service->Put(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentSwarm_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentSwarm::Service, ::agentswarm::GetRequest, ::agentswarm::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentSwarm::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agentswarm::GetRequest* req,
             ::agentswarm::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentSwarm_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentSwarm::Service, ::agentswarm::VectorSearchRequest, ::agentswarm::VectorSearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentSwarm::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agentswarm::VectorSearchRequest* req,
             ::agentswarm::VectorSearchResponse* resp) {
               return service->VectorSearch(ctx, req, resp);
             }, this)));
}

AgentSwarm::Service::~Service() {
}

::grpc::Status AgentSwarm::Service::Put(::grpc::ServerContext* context, const ::agentswarm::PutRequest* request, ::agentswarm::PutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentSwarm::Service::Get(::grpc::ServerContext* context, const ::agentswarm::GetRequest* request, ::agentswarm::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentSwarm::Service::VectorSearch(::grpc::ServerContext* context, const ::agentswarm::VectorSearchRequest* request, ::agentswarm::VectorSearchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace agentswarm
#include <grpcpp/ports_undef.inc>

