# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from single_node import agent_swarm_pb2 as single__node_dot_agent__swarm__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in single_node/agent_swarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentSwarmStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/agentswarm.AgentSwarm/Put',
                request_serializer=single__node_dot_agent__swarm__pb2.PutRequest.SerializeToString,
                response_deserializer=single__node_dot_agent__swarm__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/agentswarm.AgentSwarm/Get',
                request_serializer=single__node_dot_agent__swarm__pb2.GetRequest.SerializeToString,
                response_deserializer=single__node_dot_agent__swarm__pb2.GetResponse.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_unary(
                '/agentswarm.AgentSwarm/VectorSearch',
                request_serializer=single__node_dot_agent__swarm__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=single__node_dot_agent__swarm__pb2.VectorSearchResponse.FromString,
                _registered_method=True)


class AgentSwarmServicer:
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentSwarmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=single__node_dot_agent__swarm__pb2.PutRequest.FromString,
                    response_serializer=single__node_dot_agent__swarm__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=single__node_dot_agent__swarm__pb2.GetRequest.FromString,
                    response_serializer=single__node_dot_agent__swarm__pb2.GetResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=single__node_dot_agent__swarm__pb2.VectorSearchRequest.FromString,
                    response_serializer=single__node_dot_agent__swarm__pb2.VectorSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentswarm.AgentSwarm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentswarm.AgentSwarm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentSwarm:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentswarm.AgentSwarm/Put',
            single__node_dot_agent__swarm__pb2.PutRequest.SerializeToString,
            single__node_dot_agent__swarm__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentswarm.AgentSwarm/Get',
            single__node_dot_agent__swarm__pb2.GetRequest.SerializeToString,
            single__node_dot_agent__swarm__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentswarm.AgentSwarm/VectorSearch',
            single__node_dot_agent__swarm__pb2.VectorSearchRequest.SerializeToString,
            single__node_dot_agent__swarm__pb2.VectorSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
